# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
ItemASDF.delete_all
# . . .
ItemASDF.create!(   expense_type: 'Travel',
                amount: 600.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
)
ItemASDF.create!(   expense_type: 'Food',
                amount: 50.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
)
ItemASDF.create!(   expense_type: 'Lodging',
                amount: 300.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
)
ItemASDF.create!(   expense_type: 'Food',
                amount: 60.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
)
ItemASDF.create!(   expense_type: 'Food',
                amount: 20.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
)
ItemASDF.create!(   expense_type: 'Food',
                amount:60.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
)
ItemASDF.create!(   expense_type: 'Travel',
                amount: 900.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
)
ItemASDF.create!(   expense_type: 'Lodging',
                amount: 1000.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
)
ItemASDF.create!(   expense_type: 'Food',
                amount: 80.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
)
ItemASDF.create!(   expense_type: 'Food',
                amount: 60.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
)
ItemASDF.create!(   expense_type: 'Food',
                amount: 700.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
)
ItemASDF.create!(   expense_type: 'Food',
                amount: 65.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
)
ItemASDF.create!(   expense_type: 'Travel',
                amount: 120.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
)
ItemASDF.create!(   expense_type: 'Lodging',
                amount: 40.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
)
ItemASDF.create!(   expense_type: 'Food',
                amount: 12.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
)
ItemASDF.create!(   expense_type: 'Food',
                amount: 11.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
)
TafItem.create!(   expense_type: 'Food',
                amount: 5.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
)

# 
Item.delete_all
# . . .
Item.create!(   expense_type: 'Travel',
                amount: 600.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
                image_url: '',
)
Item.create!(   expense_type: 'Food',
                amount: 50.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
                image_url: '',
)
Item.create!(   expense_type: 'Lodging',
                amount: 300.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
                image_url: '',
)
Item.create!(   expense_type: 'Food',
                amount: 60.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
                image_url: '',
)
Item.create!(   expense_type: 'Food',
                amount: 20.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
                image_url: '',
)
Item.create!(   expense_type: 'Food',
                amount:60.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
                image_url: '',
)
Item.create!(   expense_type: 'Travel',
                amount: 900.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
                image_url: '',
)
Item.create!(   expense_type: 'Lodging',
                amount: 1000.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
                image_url: '',
)
Item.create!(   expense_type: 'Food',
                amount: 80.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
                image_url: '',
)
Item.create!(   expense_type: 'Food',
                amount: 60.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
                image_url: '',
)
Item.create!(   expense_type: 'Food',
                amount: 700.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
                image_url: '',
)
Item.create!(   expense_type: 'Food',
                amount: 65.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
                image_url: '',
)
Item.create!(   expense_type: 'Travel',
                amount: 120.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
                image_url: '',
)
Item.create!(   expense_type: 'Lodging',
                amount: 40.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
                image_url: '',
)
Item.create!(   expense_type: 'Food',
                amount: 12.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
                image_url: '',
)
Item.create!(   expense_type: 'Food',
                amount: 11.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
                image_url: '',
)
Item.create!(   expense_type: 'Food',
                amount: 5.00,
                reason: '',
                department_id: '',
                ba_approval: nil,
                ba_reject_reason: '',
                image_url: '',
)


